CREATE TABLE IF NOT EXISTS public.users(
   user_id VARCHAR (40) PRIMARY KEY,
   name VARCHAR (50) NOT NULL,
   email VARCHAR (300) UNIQUE NOT NULL,
   created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
   updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
);